export type Currency = { code: string; name: string };

// Monedas más usadas en la región y el mundo (código ISO + nombre en español).
export const CURRENCIES: Currency[] = [
  { code: "ARS", name: "Peso argentino" },
  { code: "USD", name: "Dólar estadounidense" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "Libra esterlina" },
  { code: "MXN", name: "Peso mexicano" },
  { code: "BRL", name: "Real brasileño" },
  { code: "CLP", name: "Peso chileno" },
  { code: "COP", name: "Peso colombiano" },
  { code: "PEN", name: "Sol peruano" },
  { code: "UYU", name: "Peso uruguayo" },
  { code: "PYG", name: "Guaraní paraguayo" },
  { code: "BOB", name: "Boliviano" },
  { code: "CAD", name: "Dólar canadiense" },
  { code: "CHF", name: "Franco suizo" },
  { code: "CNY", name: "Yuan chino" },
  { code: "JPY", name: "Yen japonés" },
  { code: "AUD", name: "Dólar australiano" },
  { code: "NZD", name: "Dólar neozelandés" },
  { code: "SEK", name: "Corona sueca" },
  { code: "NOK", name: "Corona noruega" },
  { code: "DKK", name: "Corona danesa" },
  { code: "PLN", name: "Zloty polaco" },
  { code: "CZK", name: "Corona checa" },
  { code: "HUF", name: "Forinto húngaro" },
  { code: "RON", name: "Leu rumano" },
  { code: "INR", name: "Rupia india" },
  { code: "KRW", name: "Won surcoreano" },
  { code: "SGD", name: "Dólar de Singapur" },
  { code: "HKD", name: "Dólar de Hong Kong" },
];
